apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook.serviceAccountName" . }}
  labels: {{- include "webhook.labels" . | nindent 4 }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}