{{- $baseCatalogs := merge (default dict .Values.catalogs) (default dict .Values.additionalCatalogs) -}}
{{- $coordinatorCatalogs := merge (default dict .Values.coordinator.additionalCatalogs) (deepCopy $baseCatalogs) -}}
{{- $workerCatalogs := merge (default dict .Values.worker.additionalCatalogs) (deepCopy $baseCatalogs) -}}

{{- if $coordinatorCatalogs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog.coordinator" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogs
    app.kubernetes.io/component-role: coordinator
data:
{{- range $catalogName, $catalogProperties := $coordinatorCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}
{{- end }}

{{- if $workerCatalogs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.catalog.worker" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogs
    app.kubernetes.io/component-role: worker
data:
{{- range $catalogName, $catalogProperties := $workerCatalogs }}
  {{ $catalogName }}.properties: |
    {{- $catalogProperties | nindent 4 }}
{{- end }}
{{- end }}
