{{- if .Values.serviceMonitor.enabled -}}
{{- $releaseLabel := "" -}}
{{- if .Values.serviceMonitor.labels -}}
  {{- $releaseLabel = default "" .Values.serviceMonitor.labels.release -}}
{{- end -}}
{{- if not $releaseLabel -}}
  {{- $releaseLabel = default "" .Values.monitoring.release -}}
{{- end -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openmetadata.fullname" . }}
  namespace: {{ coalesce .Values.serviceMonitor.namespace .Values.monitoring.namespace .Release.Namespace }}
  labels:
    {{- include "openmetadata.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $releaseLabel }}
    release: {{ $releaseLabel | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openmetadata.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: admin
      path: /prometheus
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: 10s
{{- end }}
