# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kubectl
      # Change docker.io/bitnami to your registry path
      image: registry.clemlab.com/clemlabprojects/bitnami/kubectl:sha256-00889941b4b46ce0422810f9cd24333f3881ba2cc2d7766f331d4d8505f9d4c7
    - name: os-shell
      image: registry.clemlab.com/clemlabprojects/bitnami/os-shell:sha256-028f4ddeecd0edbe82884513e2bd14268fdc8b04899a826bd840521949700857
    - name: redis
      image: registry.clemlab.com/clemlabprojects/bitnami/redis:sha256-142ab4d0c251bcf5466fffd33766350af718a6725cb926710be19fad00b2b035
    - name: redis-exporter
      image: registry.clemlab.com/clemlabprojects/bitnami/redis-exporter:sha256-00b07536265276c1c04be9072fadb8bd0a096579b1bee5b5d95922111b4983e1
    - name: redis-sentinel
      image: registry.clemlab.com/clemlabprojects/bitnami/redis-sentinel:sha256-311b86a979d47c0358692f66d0455e3a9621127da1cac1db7b88f8dfa3ef3f14
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.2.1
dependencies:
- name: common
  repository: oci://registry.clemlab.com/clemlabprojects/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: clemlab
  email: odp@clemlab.com
  url: https://github.com/clemlabprojects/trinodb-helm-charts
name: redis
sources:
- https://github.com/clemlabprojects/trinodb-helm-charts/tree/main/charts/redis
version: 23.0.4
