# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kubectl
      # Change docker.io/bitnami to your registry path
      image: registry.clemlab.com/clemlabprojects/bitnami/kubectl:1.33.4-clemlab-1
    - name: os-shell
      image: registry.clemlab.com/clemlabprojects/bitnami/os-shell:12-clemlab-1
    - name: redis
      image: registry.clemlab.com/clemlabprojects/bitnami/redis:7.4.1-clemlab-1
    - name: redis-exporter
      image: registry.clemlab.com/clemlabprojects/bitnami/redis-exporter:1.76.0-clemlab-1
    - name: redis-sentinel
      image: registry.clemlab.com/clemlabprojects/bitnami/redis-sentinel:8.2.1-clemlab-1
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.2.1
dependencies:
- name: common
  repository: oci://registry.clemlab.com/clemlabprojects/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) is an open source, advanced key-value store. It is often referred
  to as a data structure server since keys can contain strings, hashes, lists, sets
  and sorted sets.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: clemlab
  email: odp@clemlab.com
  url: https://github.com/clemlabprojects/trinodb-helm-charts
name: redis
sources:
- https://github.com/clemlabprojects/trinodb-helm-charts/tree/main/charts/redis
version: 23.0.4
